/c local p=game.player; local s=p.surface; local f=p.force; local o=p.position; local CHEST="passive-provider-chest"; local chests={}; local inv=nil; local missing={}; local function item_exists(n) return (prototypes and prototypes.item andprototypes.item[n]) or (game.item_prototypes and game.item_prototypes[n]) end; local function new_chest() local i=#chests; local x=o.x+2+(i%10); local y=o.y+math.floor(i/10); locale=s.create_entity{name=CHEST,position={x,y},force=f,raise_built=true}; if not e then e=s.create_entity{name="steel-chest",position={x,y},force=f,raise_built=true} end; if not e then return nil end; localci=e.get_inventory(defines.inventory.chest); chests[#chests+1]=ci; return ci end; inv=new_chest(); local function put(name,count) if count<=0 then return end; if not item_exists(name) then missing[#missing+1]=name; return end; localleft=count; while left>0 do if not inv then p.print("Could not place more chests. Remaining "..left.." of "..name); return end; local ins=inv.insert{name=name,count=left}; left=left-ins; if left>0 then inv=new_chest() end end end; localkit={ {"turbo-transport-belt",1610},{"bulk-inserter",680},{"turbo-underground-belt",629},{"beacon",523},{"medium-electric-pole",264},{"assembling-machine-3",100},{"pipe-to-ground",89},{"pipe",81},{"turbo-splitter",48},{"stack-inserter",40},{"foundry",15},{"big-electric-pole",14},{"display-panel",4},{"roboport",2},{"speed-module-3",1506}, {"cargo-landing-pad",1},{"construction-robot",1000},{"logistic-robot",500},{"radar",10},{"substation",80},{"solar-panel",2000},{"accumulator",1500},{"repair-pack",500},{"passive-provider-chest",100},{"requester-chest",50},{"storage-chest",50},{"buffer-chest",20},{"concrete",10000},{"landfill",5000},{"electric-mining-drill",200},{"big-mining-drill",40} }; for _,it inipairs(kit) do put(it[1],it[2]) end; p.print("Placed "..#chests.." chest(s) with Vulcanus setup kit."); if #missing>0 then p.print("Missing item prototypes: "..table.concat(missing,", ")) end


/c local p=game.player; local s=p.surface; local f=p.force; local o=p.position; local CHEST="passive-provider-chest"; local chests={}; local inv=nil; local missing={}; local function item_exists(n) return (prototypes and prototypes.item andprototypes.item[n]) or (game.item_prototypes and game.item_prototypes[n]) end; local function new_chest() local i=#chests; local x=o.x+2+(i%8); local y=o.y+math.floor(i/8); locale=s.create_entity{name=CHEST,position={x,y},force=f,raise_built=true}; if not e then e=s.create_entity{name="steel-chest",position={x,y},force=f,raise_built=true} end; if not e then return nil end; localci=e.get_inventory(defines.inventory.chest); chests[#chests+1]=ci; return ci end; inv=new_chest(); local function put(name,count) if count<=0 then return end; if not item_exists(name) then missing[#missing+1]=name; return end; localleft=count; while left>0 do if not inv then p.print("No room for "..name.." x"..left); return end; local ins=inv.insert{name=name,count=left}; left=left-ins; if left>0 then inv=new_chest() end end end; local kit={{"cargo-landing-pad",1},{"roboport",4},{"radar",8},{"construction-robot",500},{"logistic-robot",300},{"passive-provider-chest",40},{"requester-chest",20},{"storage-chest",20},{"buffer-chest",10},{"substation",60},{"big-electric-pole",80},{"medium-electric-pole",200},{"solar-panel",1200},{"accumulator",900},{"repair-pack",300},{"concrete",8000},{"landfill",3000},{"pipe",200},{"pipe-to-ground",100},{"pump",20},{"assembling-machine-3",40},{"beacon",20},{"speed-module-3",200},{"bulk-inserter",120},{"stack-inserter",80},{"turbo-transport-belt",1000},{"turbo-underground-belt",300},{"turbo-splitter",60}}; for _,it in ipairs(kit) do put(it[1],it[2]) end; p.print("Vulcanus starter spawned in "..#chests.." chest(s)."); if#missing>0 then p.print("Missing prototypes: "..table.concat(missing,", ")) end


0eJyVl9+OnCAUh1+FcFunGf7oqq/RpjdN06BLN2QZNIptNxPfvejSXdMeyeFmEoX5jr+TT4Q77eyix8k4T9s7NV7faHu4V1CrOm3DvS+L7ZVbZvJpsGoin43VhLOWl2HOo577yYzeDC7M3IZUF4bH4ZeeSGeH/pn8GCbyF9GGP5J5x3wgvCSq75fbYpUf9htkXrrZq402h2tGhsWPiw84qz+GaqYPA7T9eqezeXLKbg/u1E2H0jv0MioXHnkNM92j/k1bthbA3EPVw1y+fiuodt54o1+L7Bcv391y6/QUYAVUrKDjMJvXBtxp4FwL+hJ+1630PwSeQxAQQeQQKoggcQRxnqLMIYApqhwCmOIBR6jOU9Q5BDBFk0MAU7ArDtGcx2BIK5vzHAypZZMIgvRyK3WaBGlmZMBRkG5GBpwFaedW6zQL0s/IgLMgDY0MOAvS0a3W6aKFlDQywCwcaWlkgFn4u6bHBfw/BpeJLCKLwUGGzGJIkFFmMeB+VFmMGmQ8IBmJhZTXWQy4p00WA+ypuGYxwJ4KlsUAeyqwnibeOYH1tD7vqcB6Wid6ivU08d4KrKd1oqdIT0Vi8yWQnkYG3FOkp5EB9lQiPRWpTRzS08gAeyqRnorEN1siPY0MsKcS6WlkwD1FeioS332J9DQy4J4evvtvR5mszZisUYRt4T5FvEvamaeLtrr3k+kv2ykKiPO2ww3Hn596mvehsuKNbJpSMsk5Y+v6B8QFsV4=


0eJyFkEFPwzAMhf9K5HM60axFWjlz44DEESGUtV5rKU2ixBmbqv53su3SsQGnyPZ7n58zwdYk9IEsQzMBMY7QLHoSjN6iyb03Gr1B8aL3WjwfOOiWXcjzDmMbyDM5m1WvRrcovogH4Xa7OLiAhU+jF84Kc7Ji1+OTcIl9YhGSjYKd4AFFoH7gVQZS62yE5n2CSL3V5pTL6hEz/QoJc9baDg/QlLO8o/bkcSFS84cEtExMeOGfi+OnTeMWQ6bI+3skeBfpcuAEmfSwqiUcz2/GdxSwvUzVKccPqpJXeW5g5QJ2x77+x67+tldX9oJd0QeXbHcLWv9+VP63PYZ4rupHtak2m7oqK6XKcp6/Abttvzg=


/c local p=game.player; local e=p.surface.find_entities_filtered{name="calcite", position=p.position, radius=10000}; if #e==0 then p.print("No calcite found in 10k radius.") else local n=e[1].position; p.print("Calcite near:x="..math.floor(n.x)..", y="..math.floor(n.y).." (found "..#e.." tiles)") end