import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {decodeBlueprint,encodeBlueprint,blueprintMaterials} from '../../blueprints.mjs';
import {compactStarterLayout} from '../compact-shared-layout.mjs';
const here=path.dirname(new URL(import.meta.url).pathname);
const repo=path.resolve(here,'../../..');
const resolveRepoPath=value=>path.isAbsolute(value)?value:path.resolve(repo,value);
const source=resolveRepoPath(process.argv[2]||'.cache/science-factory/reproduce-electric/blueprint-sources/science-factories');
const out=resolveRepoPath(process.argv[3]||'.cache/science-factory/reproduce-electric/compacted');
const info=JSON.parse(await fs.readFile(path.join(source,'manifest.json')))[0];
const bp=decodeBlueprint(await fs.readFile(path.join(source,info.file),'utf8')).blueprint;
const raw=JSON.parse(await fs.readFile(path.join(repo,'.cache/factorio-vanilla/script-output/data-raw-dump.json')));
const catalog=JSON.parse(await fs.readFile(path.join(repo,'site/data/catalog.json')));
const result=compactStarterLayout(bp,info.ports,raw);
info.connectionPorts=info.ports;
const code=encodeBlueprint({blueprint:bp});
info.blueprintSha256=createHash('sha256').update(code).digest('hex');
const materials=blueprintMaterials({blueprint:bp},catalog);
info.entityCount=materials.entityCount;
info.entries=materials.entries;
info.excluded=materials.excluded;
info.footprint=result.after;
await fs.mkdir(out,{recursive:true});
await fs.writeFile(path.join(out,info.file),code+'\n');
await fs.writeFile(path.join(out,'manifest.json'),JSON.stringify([info],null,2)+'\n');
await fs.writeFile(path.join(out,'compaction.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({sha:info.blueprintSha256,entities:bp.entities.length,...result}));
