import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const base = process.env.TEST_URL || pathToFileURL(path.resolve('index.html')).href;
await fs.mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ ...(process.env.BROWSER_EXECUTABLE ? {executablePath: process.env.BROWSER_EXECUTABLE} : {channel: 'chrome'}), headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
if (base.startsWith('file:')) await context.setOffline(true);
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('response', r => { if (r.status() >= 400) errors.push(r.status() + ' ' + r.url()); });
page.on('requestfailed', r => errors.push(r.url() + ': ' + r.failure()?.errorText));
page.on('request', r => { if (base.startsWith('file:') && /^https?:/.test(r.url())) errors.push('Unexpected network request: ' + r.url()); });
async function route(name) { const url = new URL(base); url.hash = name; await page.goto(url.href); await page.getByRole('heading', { name: ({ commands: 'Command library', crates: 'Crate builder', blueprints: 'Blueprint library', production: 'Production planner', files: 'Source files', setup: 'Game setup' })[name], exact: true }).waitFor(); }
async function click(action, id) { await page.locator(`[data-action="${action}"]${id != null ? `[data-id="${id}"]` : ''}`).first().click(); }
try {
  await route('commands');
  assert.ok(await page.locator('.command-card').count() >= 18);
  await page.locator('#command-search').fill('nuclear');
  assert.ok(await page.locator('.command-card').count() >= 2);
  await click('command', 'kit-nuclear');
  assert.match(await page.locator('#command-output').inputValue(), /passive-provider-chest/);
  await click('copy-output');
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /^\/c /);
  await click('close-modal');
  await page.locator('#command-search').fill('no-such-thing-12345');
  assert.equal(await page.locator('.empty-state h3').textContent(), 'No commands found');
  await click('clear-command-search');
  await click('favorite', 'kit-nuclear');
  await page.reload();
  await page.locator('.command-card').first().waitFor();
  assert.equal(await page.locator('[data-action="favorite"][data-id="kit-nuclear"]').getAttribute('aria-pressed'), 'true');
  await page.locator('#show-history').check();
  assert.ok(await page.locator('.command-card').count() > 70);
  await page.locator('#show-history').uncheck();
  await click('give');
  await page.locator('#tool-item').fill('iron-plate');
  await page.locator('#tool-count').fill('350');
  await page.locator('#tool-quality').selectOption('rare');
  await click('build-tool', 'give');
  assert.match(await page.locator('#command-output').inputValue(), /count=350,quality=q/);
  await click('close-modal');
  await page.screenshot({ path: 'test-results/commands-desktop.png', fullPage: false });

  await route('crates');
  assert.equal(await page.locator('[data-action="generate"]').isDisabled(), true);
  await page.locator('#item-search').fill('iron plate');
  assert.equal(await page.locator('.item-tile').count(), 1);
  await click('add-item', 'iron-plate');
  await page.locator('#quantity-0').fill('4801');
  assert.match(await page.locator('.total-chests').innerText(), /2/);
  await page.locator('[data-row-quality="0"]').selectOption('legendary');
  await click('generate');
  assert.match(await page.locator('#command-output').inputValue(), /name="iron-plate",count=4801,quality="legendary"/);
  assert.equal((await page.locator('#command-output').inputValue()).includes('\n'), false);
  await click('close-modal');
  await page.locator('#quantity-0').fill('0');
  assert.equal(await page.locator('[data-action="generate"]').isDisabled(), true);
  assert.match(await page.locator('.validation-error').textContent(), /whole numbers/);
  await page.locator('#quantity-0').fill('4801');
  await page.locator('#chest-type').selectOption('requester-chest');
  assert.match(await page.locator('.chest-help').textContent(), /Robots do not take/);
  await page.locator('#chest-type').selectOption('passive-provider-chest');
  await click('save-loadout');
  await page.locator('#loadout-name').fill('Overflow test');
  await click('confirm-save');
  const downloadEvent = page.waitForEvent('download');
  await click('export-loadout');
  const download = await downloadEvent;
  await download.saveAs('test-results/loadout.json');
  await click('clear-crate');
  assert.equal(await page.locator('.manifest-row').count(), 0);
  await click('saved-loadouts');
  await click('load-saved');
  assert.equal(await page.locator('#quantity-0').inputValue(), '4801');
  await click('clear-crate');
  await page.locator('#import-file').setInputFiles('test-results/loadout.json');
  await page.locator('#quantity-0').waitFor();
  assert.equal(await page.locator('#quantity-0').inputValue(), '4801');
  await page.reload();
  await page.locator('#quantity-0').waitFor();
  assert.equal(await page.locator('#quantity-0').inputValue(), '4801');
  await click('clear-crate');
  await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"chest":"passive-provider-chest","rows":[{"id":"made-up-item","count":100}]}') });
  await page.getByText('Import failed: Unknown item: made-up-item').waitFor();
  assert.equal(await page.locator('.manifest-row').count(), 0);
  await page.locator('#item-search').fill('');
  await click('preset', 'construction');
  await page.screenshot({ path: 'test-results/crates-desktop.png', fullPage: false });

  await route('blueprints');
  assert.equal(await page.locator('.blueprint-card').count(), 24);
  await page.screenshot({ path: 'test-results/blueprints-desktop.png', fullPage: false });
  await click('explore-feature', 'solar');
  assert.equal(await page.locator('.blueprint-card').count(), 6);
  await page.locator('.blueprint-card').filter({ hasText: 'Solar (AM2)' }).first().locator('[data-action="blueprint-details"]').first().click();
  assert.ok(await page.locator('.material-list>div').count() > 0);
  await click('copy-blueprint');
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /^0e/);
  assert.match(await page.locator('.blueprint-flow').innerText(), /Petroleum gas/);
  assert.match(await page.locator('.blueprint-flow').innerText(), /Substation/);
  await page.screenshot({ path: 'test-results/blueprint-explainer.png', fullPage: false });
  await page.getByText('Construction materials', { exact: false }).filter({ hasText: 'item / quality pairs' }).first().click();
  await page.locator('#modal [data-action="pack-blueprint"]').click();
  if (await page.locator('[data-action="confirm-pack-blueprint"]').isVisible()) await click('confirm-pack-blueprint');
  await page.waitForURL(/#crates$/);
  await page.getByRole('heading', { name: 'Crate builder', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Crate builder', exact: true }).waitFor();
  assert.ok(await page.locator('.manifest-row').count() > 7);
  await click('clear-crate');
  await route('blueprints');
  await click('explore-feature', 'solar');
  await page.locator('.blueprint-card').filter({ hasText: 'Solar (AM2)' }).first().locator('[data-action="blueprint-details"]').first().click();
  await click('plan-blueprint');
  await page.waitForURL(/#production$/);
  await page.getByRole('heading', { name: 'Production planner', exact: true }).waitFor();
  assert.equal(await page.locator('.target-row').count(), 3);
  assert.equal(await page.locator('#production-boundary').inputValue(), 'blueprint');
  assert.match(await page.locator('.planner-flow>.flow-column').first().innerText(), /Petroleum gas/);
  assert.doesNotMatch(await page.locator('.planner-flow>.flow-column').first().innerText(), /Iron ore/);
  await page.locator('#production-boundary').selectOption('raw');
  assert.match(await page.locator('.planner-flow>.flow-column').first().innerText(), /Iron ore/);
  assert.match(await page.locator('.planner-flow>.flow-column').first().innerText(), /Crude oil/);
  await click('production-preset', 'solar');
  assert.equal(await page.locator('#target-0').inputValue(), '100');
  await page.locator('#target-0').fill('0');
  assert.match(await page.locator('#main [role="status"]').innerText(), /whole quantities/);
  assert.equal(await page.locator('[data-action="pack-production"]').count(), 0);
  await page.locator('#target-0').fill('200');
  await page.reload();
  await page.locator('#target-0').waitFor();
  assert.equal(await page.locator('#target-0').inputValue(), '200');
  await page.screenshot({ path: 'test-results/production-desktop.png', fullPage: false });
  await click('product-path', 'battery');
  assert.match(await page.locator('#modal .recipe-explainer').innerText(), /Sulfuric acid/);
  assert.match(await page.locator('#modal').innerText(), /Blueprints that produce this item/);
  await click('close-modal');
  const planDownloadEvent = page.waitForEvent('download');
  await click('production-export');
  const planDownload = await planDownloadEvent;
  await planDownload.saveAs('test-results/production-plan.json');
  const exportedPlan = JSON.parse(await fs.readFile('test-results/production-plan.json', 'utf8'));
  assert.equal(exportedPlan.targets.find(t => t.id === 'solar-panel').count, 200);
  assert.ok(exportedPlan.raw.some(t => t.id === 'crude-oil'));
  await click('pack-production', 'raw');
  await page.waitForURL(/#crates$/);
  await page.getByRole('heading', { name: 'Crate builder', exact: true }).waitFor();
  const solidInputs = await page.locator('.manifest-items').innerText();
  assert.match(solidInputs, /Iron ore/);
  assert.doesNotMatch(solidInputs, /Crude oil|Water/);
  await click('clear-crate');
  await route('production');
  await click('production-preset', 'robots');
  assert.equal(await page.locator('.target-row').count(), 5);
  await click('pack-production', 'targets');
  await page.waitForURL(/#crates$/);
  await page.getByRole('heading', { name: 'Crate builder', exact: true }).waitFor();
  assert.equal(await page.locator('.manifest-row').count(), 5);
  await click('generate');
  assert.match(await page.locator('#command-output').inputValue(), /name="construction-robot",count=50/);
  await click('close-modal');
  await route('production');
  await page.locator('#production-item').fill('uranium-fuel-cell');
  await page.getByRole('button', { name: 'Add product', exact: true }).click();
  assert.match(await page.locator('.planner-assumptions').innerText(), /Supply separately:.*Uranium-235/);
  await click('production-preset', 'solar');
  await route('blueprints');
  await page.locator('#blueprint-category').selectOption('Aquilo');
  assert.ok(await page.locator('.blueprint-card').count() > 10);
  await click('explore-feature', 'all');
  await click('blueprint-page', '1');
  assert.match(await page.locator('.results-heading').innerText(), /page 2/);
  await page.locator('#blueprint-direction').selectOption('outputs');
  await page.locator('#blueprint-search').fill('substation');
  assert.ok(await page.locator('.blueprint-card').count() >= 3);
  await route('files');
  await page.locator('#file-search').fill('commands.md');
  assert.equal(await page.locator('.file-table tbody tr').count(), 1);
  const href = await page.locator('.file-table tbody td:first-child a').getAttribute('href');
  const source = new URL(href, page.url());
  if (source.protocol === 'file:') assert.match(await fs.readFile(fileURLToPath(source), 'utf8'), /Factorio/);
  else assert.equal((await page.request.get(source.href)).status(), 200);
  await route('setup');
  assert.match(await page.locator('.setup-card').innerText(), /Manual grants stay available/);

  for (const width of [390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    for (const name of ['commands', 'crates', 'blueprints', 'production', 'files', 'setup']) {
      await route(name);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${name} overflows at ${width}px`);
      if (width === 390 && ['commands', 'crates', 'blueprints', 'production'].includes(name)) await page.screenshot({ path: `test-results/${name}-mobile.png`, fullPage: false });
    }
  }
  assert.deepEqual(errors, []);
  // Verify the copy fallback when both browser clipboard mechanisms are blocked.
  await route('commands');
  await click('command', 'kit-nuclear');
  const commandText = await page.locator('#command-output').inputValue();
  await page.evaluate(() => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('Clipboard blocked')) } });
    document.execCommand = () => false;
  });
  await click('copy-output');
  await page.locator('#fallback-copy').waitFor();
  assert.equal(await page.locator('#fallback-copy').inputValue(), commandText);
  assert.equal(await page.locator('#fallback-copy').evaluate(e => e.selectionEnd - e.selectionStart), commandText.length);
  // The standalone folder must also open directly, without the root launcher.
  await page.goto(pathToFileURL(path.resolve('dist/index.html')).href);
  await page.getByRole('heading', { name: 'Command library', exact: true }).waitFor();
  assert.ok(await page.locator('.command-card').count() >= 18);
  await page.goto(pathToFileURL(path.resolve('dist/index.html')).href + '#production');
  await page.getByRole('heading', { name: 'Production planner', exact: true }).waitFor();
  assert.equal(await page.locator('.target-row').count(), 3);
  assert.deepEqual(errors, []);
  console.log('Offline file:// browser checks passed: search, clipboard and fallback, favorites, quantities, qualities, overflow, saved loadouts, import/export, blueprints, local sources, setup, production chains, fluid separation, recipe boundaries, and 24 responsive page/viewport combinations.');
} catch (error) {
  await page.screenshot({ path: 'test-results/browser-failure.png', fullPage: false });
  console.error('Browser errors:', errors);
  throw error;
} finally { await browser.close(); }
