import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { decodeBlueprint } from '../scripts/blueprints.mjs';
import { generateCrateCommand } from '../scripts/packer.mjs';
const base=process.env.TEST_URL || pathToFileURL(path.resolve('index.html')).href;
const catalog=JSON.parse(await fs.readFile('site/data/catalog.json','utf8'));
const library=JSON.parse(await fs.readFile('site/data/library.json','utf8'));
const source=await fs.readFile('power/fusion_reactor_1_2gw.txt','utf8');
const blueprint=library.blueprints.find(b=>b.name==='Fusion Reactor (1.2GW)');
assert.ok(blueprint);
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
if(base.startsWith('file:')) await context.setOffline(true);
const page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('requestfailed',r=>errors.push(r.url()));
async function openBlueprint(){
  const url=new URL(base);url.hash='blueprints';
  if(page.url()===url.href) await page.reload(); else await page.goto(url.href);
  if(await page.locator('#modal[open]').count()) await page.locator('[data-action="close-modal"]').click();
  await page.locator('#blueprint-source').selectOption('Local');
  await page.locator('#blueprint-search').fill('Fusion Reactor');
  const card=page.locator('.blueprint-card').filter({has:page.getByRole('heading',{name:blueprint.name,exact:true})});
  assert.equal(await card.count(),1);
  await card.getByRole('button',{name:'Inputs & outputs',exact:true}).click();
}
try{
  await openBlueprint();
  // Quick generation is for this blueprint alone and preserves another saved loadout.
  await page.evaluate(()=>localStorage.setItem('factorio-center-v1',JSON.stringify({rows:[{id:'iron-plate',count:7,quality:'rare'}],chest:'steel-chest'})));
  await openBlueprint();
  await page.locator('#modal [data-action="copy-blueprint"]').click();
  assert.deepEqual(decodeBlueprint(await page.evaluate(()=>navigator.clipboard.readText())),decodeBlueprint(source));
  assert.equal(await page.locator('#modal .supply-card').count(),2);
  assert.match(await page.locator('#modal .operating-guide').innerText(),/4,000 Fluoroketone \(Cold\)/);
  assert.equal(await page.locator('#modal .delivery-support [data-action="product-path"]').count(),3);
  assert.match(await page.locator('#modal .blueprint-flow .flow-column').first().innerText(),/Fusion power cell/);
  assert.doesNotMatch(await page.locator('#modal .blueprint-flow .flow-column').first().innerText(),/Fluoroketone/);
  assert.match(await page.locator('#modal .blueprint-flow .finished').innerText(),/Electricity/);
  assert.doesNotMatch(await page.locator('#modal .blueprint-flow .finished').innerText(),/Fluoroketone/);
  await page.screenshot({path:'test-results/fusion-blueprint-desktop.png'});
  await page.locator('#modal [data-action="crate-blueprint"]').click();
  const code=await page.locator('#command-output').inputValue();
  assert.equal(code,generateCrateCommand(blueprint.entries,catalog,'passive-provider-chest'));
  assert.match(await page.locator('.generated-summary').innerText(),/152 items\. 1 chest/);
  assert.ok(!code.includes('fusion-power-cell'));
  await page.locator('[data-action="copy-output"]').click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),code);
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('factorio-center-v1')).rows),[{id:'iron-plate',count:7,quality:'rare'}]);
  await fs.writeFile('test-results/fusion-construction-crate.lua',code+'\n');
  await page.screenshot({path:'test-results/fusion-construction-crate.png'});
  await openBlueprint();
  await page.locator('#modal [data-action="plan-blueprint-inputs"]').click();
  await page.waitForURL(/#production$/);
  await page.getByRole('heading',{name:'Production planner',exact:true}).waitFor();
  assert.equal(await page.locator('.target-row').count(),2);
  assert.equal(await page.locator('#production-boundary').inputValue(),'raw');
  assert.equal(await page.getByLabel('Quantity of Fusion power cell',{exact:true}).inputValue(),'20');
  assert.equal(await page.getByLabel('Quantity of Fluoroketone (Cold)',{exact:true}).inputValue(),'4000');
  assert.match(await page.locator('.planner-flow').innerText(),/Ammoniacal solution/);
  assert.match(await page.locator('.planner-flow').innerText(),/Lithium brine/);
  assert.equal(await page.locator('#main [role="status"]').count(),0);
  const event=page.waitForEvent('download');
  await page.locator('[data-action="production-export"]').click();
  const download=await event;await download.saveAs('test-results/fusion-supply-plan.json');
  const plan=JSON.parse(await fs.readFile('test-results/fusion-supply-plan.json','utf8'));
  assert.deepEqual(plan.external,[]);
  assert.ok(plan.steps.some(s=>s.id==='fluoroketone'));
  assert.ok(plan.steps.some(s=>s.id==='ammoniacal-solution-separation'));
  await page.locator('[data-action="pack-production"][data-id="targets"]').click();
  await page.waitForURL(/#crates$/);
  await page.getByRole('heading',{name:'Crate builder',exact:true}).waitFor();
  const rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('factorio-center-v1')).rows);
  assert.deepEqual(rows.find(r=>r.id==='fusion-power-cell'),{id:'fusion-power-cell',count:20,quality:'normal'});
  assert.ok(!rows.some(r=>r.id.includes('fluoroketone')));
  assert.ok(rows.some(r=>r.id==='iron-plate'&&r.count===7&&r.quality==='rare'));
  await openBlueprint();
  await page.locator('#modal .supply-card').last().getByRole('button',{name:'Plan from raw resources',exact:true}).click();
  await page.waitForURL(/#production$/);
  await page.getByRole('heading',{name:'Production planner',exact:true}).waitFor();
  assert.equal(await page.locator('.target-row').count(),1);
  assert.equal(await page.getByLabel('Quantity of Fluoroketone (Cold)',{exact:true}).inputValue(),'10');
  await page.setViewportSize({width:390,height:844});
  await openBlueprint();
  await page.locator('#modal').evaluate(async e => { const imgs=[...e.querySelectorAll('img')]; for (const img of imgs) img.loading='eager'; await Promise.all(imgs.map(img=>img.decode().catch(()=>{}))); });
  assert.ok(await page.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  await page.screenshot({path:'test-results/fusion-blueprint-mobile.png'});
  await page.locator('#modal .supply-card').last().scrollIntoViewIfNeeded();
  assert.ok(await page.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  await page.screenshot({path:'test-results/fusion-supplies-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('Fusion website passed: exact import, isolated 152-item crate, clipboard, complete raw supply chains, fluid exclusion, preserved loadout, desktop and mobile.');
}finally{await browser.close();}
